### ISSUE TITLE
Speedometer and ring gauge incorrect size with label

### ISSUE THREAD

**Issue by jdorko** [sibvisions/gauges#1]
If speedometer or ring gauge have the label set, and there is an another component below, the components overlap eachother.
It seems, the size is set only for gauge svg part. 
[
![image](https://user-images.githubusercontent.com/90700700/134907290-40eaa4b2-9dad-4bc1-a556-d1e450b0300e.png)
](url)

**Comment by gimmixAT** [comment]
Have the gauge wrappers in your layout a limited height as well? 
In the library demo it looks correct. Currently the size only sets the viewBox and sizes of the created svg. If the title should also be taken into account we should probably add a width & height option. But this will ned multiple internal passes because we need to render & measure the title before we can render the gauge.

**Comment by gimmixAT** [comment]
I implemented a small css tweak so that gauges can scale down if the height of the parent is less than the gauge + title height

**Comment by jdorko** [comment]
Unfortunately the problem remains. The parent div had had height and width set to 100%. I changed it to 300px in order to test your tweak, but i got the same behaviour. I tried to pass smaller height into gauge, it didn´t help neither. 
The mentioned parent div has another parent div, which have height and width corresponding to preferred size(300px,300px) and corresponds to the vaadin gauge component. I think, this just can´t contain elements, that have greater size, otherwise vaadin layout gets broken.
So try render & measure the title, please.

**Comment by gimmixAT** [comment]
Could you maybe paste a html snippet of the DOM around the gauges in the vaadin client? Then I should be able to better reproduce the issue.

**Comment by jdorko** [comment]
![image](https://user-images.githubusercontent.com/90700700/135254515-784d9a17-4ce3-4261-b261-0fa7c7f11e3d.png)

**Comment by gimmixAT** [comment]
If you can give the wrapping blank div a `style="height: 100%"` it should work now.
In case that doesn't work, there is now a width & height option you can set for a gauge to set an exact px size.
